server:
  port: 9090
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521/Orcl
    username: system
  jpa:
    hibernate:
      ddl-auto: update
unlock-app:
    messages:
    accUnlockSuccess: Your Account Unlocked Successfully
    InvalidTempPwd: Invalid Temporary Password
     